// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b1jHtzznz5qfWCWxvSbcUi
// Component: gACe1O_O0u
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_plasmic_test.module.css"; // plasmic-import: b1jHtzznz5qfWCWxvSbcUi/projectcss
import sty from "./PlasmicBenefitsCardWithIcon.module.css"; // plasmic-import: gACe1O_O0u/css

import EnvelopeIconsvgIcon from "./icons/PlasmicIcon__EnvelopeIconsvg"; // plasmic-import: J33e3XWQn/icon

export type PlasmicBenefitsCardWithIcon__VariantMembers = {};

export type PlasmicBenefitsCardWithIcon__VariantsArgs = {};
type VariantPropType = keyof PlasmicBenefitsCardWithIcon__VariantsArgs;
export const PlasmicBenefitsCardWithIcon__VariantProps =
  new Array<VariantPropType>();

export type PlasmicBenefitsCardWithIcon__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};

type ArgPropType = keyof PlasmicBenefitsCardWithIcon__ArgsType;
export const PlasmicBenefitsCardWithIcon__ArgProps = new Array<ArgPropType>(
  "children",
  "slot"
);

export type PlasmicBenefitsCardWithIcon__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultBenefitsCardWithIconProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  className?: string;
}

function PlasmicBenefitsCardWithIcon__RenderFunc(props: {
  variants: PlasmicBenefitsCardWithIcon__VariantsArgs;
  args: PlasmicBenefitsCardWithIcon__ArgsType;
  overrides: PlasmicBenefitsCardWithIcon__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <EnvelopeIconsvgIcon
            className={classNames(projectcss.all, sty.svg__xObiI)}
            role={"img"}
          />
        ),

        value: args.children
      })}

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {p.renderPlasmicSlot({
          defaultContents: " Keine Bonitäts-\nprüfung",
          value: args.slot,
          className: classNames(sty.slotTargetSlot)
        })}
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBenefitsCardWithIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBenefitsCardWithIcon__VariantsArgs;
    args?: PlasmicBenefitsCardWithIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBenefitsCardWithIcon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBenefitsCardWithIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBenefitsCardWithIcon__ArgProps,
      internalVariantPropNames: PlasmicBenefitsCardWithIcon__VariantProps
    });

    return PlasmicBenefitsCardWithIcon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBenefitsCardWithIcon";
  } else {
    func.displayName = `PlasmicBenefitsCardWithIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicBenefitsCardWithIcon = Object.assign(
  // Top-level PlasmicBenefitsCardWithIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicBenefitsCardWithIcon
    internalVariantProps: PlasmicBenefitsCardWithIcon__VariantProps,
    internalArgProps: PlasmicBenefitsCardWithIcon__ArgProps
  }
);

export default PlasmicBenefitsCardWithIcon;
/* prettier-ignore-end */
