// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b1jHtzznz5qfWCWxvSbcUi
// Component: TciHbiRyoi
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_plasmic_test.module.css"; // plasmic-import: b1jHtzznz5qfWCWxvSbcUi/projectcss
import sty from "./PlasmicComparisonTableRow.module.css"; // plasmic-import: TciHbiRyoi/css

import Section8Icon1SvgIcon from "./icons/PlasmicIcon__Section8Icon1Svg"; // plasmic-import: wPntU_KHu/icon

export type PlasmicComparisonTableRow__VariantMembers = {};

export type PlasmicComparisonTableRow__VariantsArgs = {};
type VariantPropType = keyof PlasmicComparisonTableRow__VariantsArgs;
export const PlasmicComparisonTableRow__VariantProps =
  new Array<VariantPropType>();

export type PlasmicComparisonTableRow__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
};

type ArgPropType = keyof PlasmicComparisonTableRow__ArgsType;
export const PlasmicComparisonTableRow__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2"
);

export type PlasmicComparisonTableRow__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultComparisonTableRowProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  className?: string;
}

function PlasmicComparisonTableRow__RenderFunc(props: {
  variants: PlasmicComparisonTableRow__VariantsArgs;
  args: PlasmicComparisonTableRow__ArgsType;
  overrides: PlasmicComparisonTableRow__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <Section8Icon1SvgIcon
            className={classNames(projectcss.all, sty.svg__snUNd)}
            role={"img"}
          />
        ),

        value: args.children
      })}

      <div className={classNames(projectcss.all, sty.freeBox__pJDlg)}>
        <div className={classNames(projectcss.all, sty.freeBox__qjmxh)}>
          {p.renderPlasmicSlot({
            defaultContents: "Material",
            value: args.slot,
            className: classNames(sty.slotTargetSlot)
          })}
        </div>

        <div className={classNames(projectcss.all, sty.freeBox__guPg6)}>
          <div className={classNames(projectcss.all, sty.freeBox__yEf0V)}>
            {p.renderPlasmicSlot({
              defaultContents: "Millionen Akzeptanzstellen",
              value: args.slot2,
              className: classNames(sty.slotTargetSlot2)
            })}
          </div>
        </div>
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicComparisonTableRow__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicComparisonTableRow__VariantsArgs;
    args?: PlasmicComparisonTableRow__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicComparisonTableRow__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicComparisonTableRow__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicComparisonTableRow__ArgProps,
      internalVariantPropNames: PlasmicComparisonTableRow__VariantProps
    });

    return PlasmicComparisonTableRow__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicComparisonTableRow";
  } else {
    func.displayName = `PlasmicComparisonTableRow.${nodeName}`;
  }
  return func;
}

export const PlasmicComparisonTableRow = Object.assign(
  // Top-level PlasmicComparisonTableRow renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicComparisonTableRow
    internalVariantProps: PlasmicComparisonTableRow__VariantProps,
    internalArgProps: PlasmicComparisonTableRow__ArgProps
  }
);

export default PlasmicComparisonTableRow;
/* prettier-ignore-end */
